apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command: ["/bin/sh", "-c"]
    args: ["echo Hello, busybox!; sleep 3000;"]
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
