apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
      protocol: TCP
  selector:
    app: zookeeper
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
      protocol: TCP
    - name: cluster
      port: 2888
      targetPort: 2888
      protocol: TCP
    - name: election
      port: 3888
      targetPort: 3888
      protocol: TCP
  selector:
    app: zookeeper
  type: ClusterIP
  clusterIP: None
