apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-ha
    role: service
  name: redis-sentinel
spec:
  ports:
  - port: 26379
    protocol: TCP
    targetPort: 26379
  selector:
    redis-sentinel: "true"
  sessionAffinity: None
