---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: serving-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/serving/model
    server: 172.16.35.9

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: serving-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
