---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ig-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/ig
    server: 172.16.35.9

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ig-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
