---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bg-tmp-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/bg/tmp
    server: 172.16.35.9
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bg-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/bg/data
    server: 172.16.35.9

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bg-tmp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bg-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
