apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
   name: small
provisioner: kubernetes.io/rbd
parameters:
    monitors: MONITORS
    adminId: admin
    adminSecretName: admin-key
    adminSecretNamespace: "kube-system"
    pool: kube
    userId: kube
    userSecretName: kube-key
