apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: manage-iq
  namespace: default
  labels:
    app: manage-iq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manage-iq
  template:
    metadata:
      labels:
        app: manage-iq
        version: "0.2"
        environment: development
        provider: do
    spec:
      containers:
      - name: manage-iq
        # http://manageiq.org/docs/get-started/docker
        image: manageiq/manageiq:euwe-2
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: "/"
            port: 443
          initialDelaySeconds: 60
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: "/"
            port: 443
          initialDelaySeconds: 30
          timeoutSeconds: 1
        ports:
          - containerPort: 443
        securityContext:
          privileged: true
