apiVersion: v1
kind: Service
metadata:
  name: manage-iq-svc
  namespace: default
  labels:
    app: manage-iq
spec:
  type: LoadBalancer
  externalIPs:
  - 172.16.35.9
  ports:
    # 443:  Secure HTTPS port
  - name: peer-service
    port: 8443
    targetPort: 443
    protocol: TCP
  selector:
    app: manage-iq
