apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    name: kafka
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    name: kafka
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka-headless"
  # used 3 replicas in order to have alwayas majority for leader election
  replicas: 3
  template:
    metadata:
      labels:
        name: kafka
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
       - name: volume-mount-hack
         image: busybox
         command: ["sh", "-c", "chown -R 1001:1001 /var/lib/kafka/"]
         volumeMounts:
           - name: kafka-storage
             mountPath: /var/lib/kafka/
      containers:
        - name: kafka
          image: kairen/kafka:v1.0.0
          env:
            - name: KAFKA_ADVERTISED_HOST
              value: "172.22.132.10"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            - name: KAFKA_ADVERTISED_PROTOCOL_NAME
              value: OUTSIDE
            - name: KAFKA_ADVERTISED_PORT
              value: "9094"
            - name: KAFKA_PROTOCOL_NAME
              value: INSIDE
            - name: KAFKA_PORT
              value: "9092"
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/
          livenessProbe:
            exec:
              command:
              - "/opt/kafka/kafka_healthcheck.sh"
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - "/opt/kafka/kafka_healthcheck.sh"
            initialDelaySeconds: 15
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        storageClassName: rbd
        resources:
          requests:
            storage: 5Gi
        accessModes: [ "ReadWriteOnce" ]
