apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
   name: rbd
provisioner: kubernetes.io/rbd
parameters:
    monitors: 172.22.132.101:6789,172.22.132.102:6789,172.22.132.103:6789
    adminId: admin
    adminSecretName: admin-key
    adminSecretNamespace: kube-system
    pool: kube
    userId: kube
    userSecretName: kube-key
